---
- name: Unix based OS setting by ansible
  hosts: localhost
  connection: local
  become: no

  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"

  roles:
    - role: homebrew
      tags: homebrew
    - role: anyenv
      tags: anyenv
    - role: python
      tags: python
    - role: fish
      tags: fish
    - role: js
      tags: js